services:
  - type: web
    name: BackWeb-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt; python manage.py collectstatic --no-input; python manage.py migrate"
    startCommand: "gunicorn BackWeb.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "BackWeb-backend.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        value: postgres://postgres.tjaialnqzdhggmycexwz:mataronakeny@aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SUPABASE_URL
        value: "https://tjaialnqzdhggmycexwz.supabase.co"
      - key: SUPABASE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYWlhbG5xemRoZ2dteWNleHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzY5NzQsImV4cCI6MjA1MTE1Mjk3NH0.temp_key"
    healthCheckPath: "/api/"